# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

jobs:
- deployment: VMDeploy
  displayName: 'Deploy to Azure VM'
  environment:
    name: keyscribe-azure-vm
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Docker@2
          displayName: 'Build and Deploy Backend'
          inputs:
            command: 'build'
            Dockerfile: './backend/Dockerfile'
        
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'dockerhub'
            dockerComposeFile: '**/docker-compose.yml'
            action: 'Run a Docker Compose command'
            dockerComposeCommand: 'up'


  
