version: "3.8"

services:
  postgres:
    image: postgres:15.5-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ks_db
      POSTGRES_USER: keyscribe
      POSTGRES_PASSWORD: K3yscr1b3
    volumes:
      - postgres_data:/var/lib/postgresql:ro
      - ./backend/dbbackup.sql:/docker-entrypoint-initdb.d/dbexport.sql
    # ports:
    #   - '5432:5432'
    network_mode: host

  frontend: 
    build: ./frontend
    container_name: frontend_container
    environment:
      REACT_APP_BACKEND_URL: https://localhost:8000/api
    # ports:
    #   - "3000:3000"
    network_mode: host
  
  backend:
    build: ./backend
    container_name: backend_container
    environment:
      NODE_ENV: production
      PORT: 8000
      DEV_BACKEND: https://localhost:8000
      JWT_SECRET: 'super_special_secret'
      SESSION_SECRET: 'super_special_secret_session'
      DB_PASSWORD: 'K3yscr1b3'
      DB_HOST: '52.168.92.118'
      FRONTEND_CORS: http://localhost:3000
    # ports:
    #   - "8000:8000"
    network_mode: host
    
volumes:
  postgres_data: {}

networks:
  keyscribe_network: